version: '3.4'
services:

  db:
    image: postgres:9.6-alpine
    env_file: env/db.env
    networks:
      - nemushee_internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mastodon", "-d", "mastodon_production"]
    volumes:
      - nemushee_postgres_v2:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.labels.nemushee_db_available == true]

  redis:
    image: redis:6.0-alpine
    networks:
      - nemushee_internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis:/data
    deploy:
      placement:
        constraints: [node.labels.nemushee_db_available == true]

  web:
    image: ghcr.io/katonux/nemushee/mastodon:3.3.0
    env_file:
      - env/production.env
      - env/web.env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - traefik_ingress
      - nemushee_internal
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_ingress"
        - "traefik.http.routers.nemushee-puma.tls=true"
        - "traefik.http.routers.nemushee-puma.tls.certresolver=myresolver"
        - "traefik.http.routers.nemushee-puma.rule=Host(`nemushee.net`)"
        - "traefik.http.routers.nemushee-puma.entrypoints=websecure"
        - "traefik.http.routers.nemushee-puma.middlewares=streaming-redirect"
        - "traefik.http.services.puma.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.streaming-redirect.redirectregex.regex=^(https|wss)://nemushee.net/api/v1/streaming(.*)$$"
        - "traefik.http.middlewares.streaming-redirect.redirectregex.replacement=$${1}://stream.nemushee.net/api/v1/streaming$${2}"
      replicas: 8
      placement:
        constraints: [node.labels.nemushee_web_available == true]

  storage:
    image: minio/minio
    volumes:
      - storage:/export:z
    networks:
      - traefik_ingress
      - nemushee_internal
    env_file: env/minio.env
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_ingress"
        - "traefik.http.routers.nemushee-minio.tls=true"
        - "traefik.http.routers.nemushee-minio.tls.certresolver=myresolver"
        - "traefik.http.routers.nemushee-minio.rule=Host(`media.nemushee.net`)"
        - "traefik.http.routers.nemushee-minio.entrypoints=websecure"
        - "traefik.http.services.minio.loadbalancer.server.port=9000"
      placement:
        constraints: [node.labels.nemushee_storage_available == true]

  streaming:
    image: ghcr.io/katonux/nemushee/mastodon:3.3.0
    env_file:
      - env/production.env
      - env/streaming.env
    command: node ./streaming
    networks:
      - traefik_ingress
      - nemushee_internal
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_ingress"
        - "traefik.http.routers.nemushee-stream.tls=true"
        - "traefik.http.routers.nemushee-stream.tls.certresolver=myresolver"
        - "traefik.http.routers.nemushee-stream.rule=Host(`stream.nemushee.net`)"
        - "traefik.http.routers.nemushee-stream.entrypoints=websecure"
        - "traefik.http.services.stream.loadbalancer.server.port=4000"
      replicas: 4
      placement:
        constraints: [node.labels.nemushee_streaming_available == true]

  sidekiq:
    image: ghcr.io/katonux/nemushee/mastodon:3.3.0
    env_file: env/production.env
    command: bundle exec sidekiq -c 1
    networks:
      - nemushee_internal
    deploy:
      replicas: 8
      resources:
        limits:
          memory: 512M
      placement:
        constraints: [node.labels.nemushee_sidekiq_available == true]

  es:
    image: elasticsearch:7.10.1
    env_file: env/es.env
    networks:
      - nemushee_internal
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nemushee_es_available == true]

volumes:
  nemushee_postgres_v2:
   external: true
  redis:
    driver: local
  sidekiq:
    driver: local
  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/disk2t/nemushee
  elasticsearch:
    driver: local

networks:
  traefik_ingress:
    driver: overlay
    external: true
  nemushee_internal:
    internal: true
    external: true
