version: '3.4'

services:
  es:
    image: elasticsearch:7.10.1
    env_file: ../env/es.env
    networks:
      - nemushee_internal
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.nemushee_es_available == true]