version: '3.4'

services:
  redis:
    image: redis:6.0-alpine
    networks:
      - nemushee_internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis:/data
    deploy:
      placement:
        constraints: [node.labels.nemushee_db_available == true]