version: '3.4'

services:
  # storage-a:
  #   image: minio/minio
  #   volumes:
  #     - storage-a:/export:z
  #   networks:
  #     - traefik_ingress
  #     - nemushee_internal
  #   env_file: ../env/minio.env
  #   command: server /export
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   deploy:
  #     labels:
  #       - "traefik.enable=true"
  #       - "traefik.docker.network=traefik_ingress"
  #       - "traefik.http.routers.nemushee-storage.tls=true"
  #       - "traefik.http.routers.nemushee-storage.tls.certresolver=myresolver"
  #       - "traefik.http.routers.nemushee-storage.rule=Host(`media.nemushee.net`)"
  #       - "traefik.http.routers.nemushee-storage.entrypoints=websecure"
  #       - "traefik.http.services.storage.loadbalancer.server.port=9000"
  #     placement:
  #       constraints: [node.labels.nemushee_storage-a_available == true]

  storage-b:
    image: minio/minio
    volumes:
      - storage-b:/export:z
    networks:
      - traefik_ingress
      - nemushee_internal
    env_file: ../env/minio.env
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_ingress"
        - "traefik.http.routers.nemushee-storage.tls=true"
        - "traefik.http.routers.nemushee-storage.tls.certresolver=myresolver"
        - "traefik.http.routers.nemushee-storage.rule=Host(`media.nemushee.net`)"
        - "traefik.http.routers.nemushee-storage.entrypoints=websecure"
        - "traefik.http.services.storage.loadbalancer.server.port=9000"
      placement:
        constraints: [node.labels.nemushee_storage-b_available == true]

  # mc:
  #   image: minio/mc
  #   networks:
  #     - nemushee_internal
  #   entrypoint: tail -f /dev/null
  #   deploy:
  #     placement:
  #       constraints: [node.hostname == spt-node-cran]